name: Deploy Static Website to Azure Blob

on:
  push:
    branches:
      - main  # change if your branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Upload files to Azure Blob
      run: |
        az storage blob upload-batch \
          --account-name belayakassanew \
          --destination \$web \
          --source . \
          --overwrite
      env:
        AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
